source 'https://rubygems.org'

ruby '1.9.3'

gem 'rails', '3.2.11'
gem 'sqlite3', group: :development
gem 'pg', group: :production
gem 'thin'
gem 'sass', '~> 3.2.15'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'therubyracer'
gem 'less-rails-bootstrap'
gem 'twitter-bootstrap-rails'
gem 'authlogic', '~> 3.4.0'
gem 'scrypt'
gem 'bcrypt'
gem 'simple-private-messages', '0.0.0', :git => 'git://github.com/jongilbraith/simple-private-messages.git'
gem 'acts_as_commentable_with_threading'
gem 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
gem 'obscenity'
gem 'will_paginate', '~> 3.0'
gem 'tinymce-rails'
gem 'rails_12factor'
gem 'omniauth-facebook'
gem 'certified'
gem 'font-awesome-rails'
